-- ─────────────────────────────────────────────────────────────────────────────
-- Bodega Bühlot — Phase F: Schichtplanung + Telegram-Onboarding
--
-- Adds:
--   1. user_roles.telegram_chat_id     — links a Bloom user to their Telegram
--      chat. Populated by the bot webhook after the staff member starts the
--      bot with their one-time onboarding code.
--   2. user_roles.telegram_invite_code — one-time code generated by the
--      owner; consumed and cleared once the chat ID is captured.
--   3. shifts                          — published roster entries
--      (date, start, end, role, notes).
--   4. shift_assignments               — links a shift to a user.
--   5. shift_swaps                     — pending/approved/rejected swap
--      requests, decided by owner/manager.
--
-- All new tables are RLS-protected analogous to migrations 0001/0002.
-- Idempotent.
--
-- Numbered 0004 (not 0003) because 0003_seed.sql already occupies the 0003
-- slot in the migration table. Without this rename, `supabase db push`
-- considers version 0003 done and skips this migration entirely.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Telegram fields on user_roles ────────────────────────────────────────
alter table user_roles
  add column if not exists telegram_chat_id text,
  add column if not exists telegram_invite_code text,
  add column if not exists telegram_linked_at timestamptz;

create unique index if not exists idx_user_roles_telegram_invite_code
  on user_roles (telegram_invite_code)
  where telegram_invite_code is not null;

create unique index if not exists idx_user_roles_telegram_chat_id
  on user_roles (telegram_chat_id)
  where telegram_chat_id is not null;

-- ── 2. Shift role enum ──────────────────────────────────────────────────────
do $$ begin
  create type shift_role as enum ('service', 'kitchen', 'bar', 'host', 'manager_on_duty');
exception when duplicate_object then null; end $$;

do $$ begin
  create type shift_swap_status as enum ('pending', 'approved', 'rejected', 'cancelled');
exception when duplicate_object then null; end $$;

-- ── 3. Shifts ───────────────────────────────────────────────────────────────
create table if not exists shifts (
  id          uuid primary key default uuid_generate_v4(),
  date        date not null,
  start_time  time not null,
  end_time    time not null,
  role        shift_role not null default 'service',
  notes       text,
  published   boolean not null default false,
  created_by  uuid references auth.users(id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_shifts_date on shifts (date);
create index if not exists idx_shifts_published on shifts (published);

-- ── 4. Shift assignments ────────────────────────────────────────────────────
create table if not exists shift_assignments (
  id          uuid primary key default uuid_generate_v4(),
  shift_id    uuid not null references shifts(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (shift_id, user_id)
);

create index if not exists idx_assignments_user on shift_assignments (user_id);

-- ── 5. Swap requests ────────────────────────────────────────────────────────
create table if not exists shift_swaps (
  id              uuid primary key default uuid_generate_v4(),
  assignment_id   uuid not null references shift_assignments(id) on delete cascade,
  requester_id    uuid not null references auth.users(id) on delete cascade,
  reason          text,
  status          shift_swap_status not null default 'pending',
  decided_by      uuid references auth.users(id),
  decided_at      timestamptz,
  decision_note   text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_swaps_status on shift_swaps (status);
create index if not exists idx_swaps_requester on shift_swaps (requester_id);

-- ── 6. updated_at trigger for shifts ────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_shifts_updated') then
    create trigger trg_shifts_updated
      before update on shifts
      for each row execute function set_updated_at();
  end if;
end $$;

-- ── 7. RLS ──────────────────────────────────────────────────────────────────
alter table shifts             enable row level security;
alter table shift_assignments  enable row level security;
alter table shift_swaps        enable row level security;

-- Shifts: staff sees only published shifts they are assigned to OR all
-- published shifts. Manager+ see everything.
drop policy if exists shifts_staff_read on shifts;
create policy shifts_staff_read on shifts
  for select using (
    published
    or bloom_has_role(array['owner','manager']::bloom_role[])
  );

drop policy if exists shifts_manager_write on shifts;
create policy shifts_manager_write on shifts
  for all using (bloom_has_role(array['owner','manager']::bloom_role[]))
         with check (bloom_has_role(array['owner','manager']::bloom_role[]));

-- Assignments: each user sees own; manager+ sees all and writes.
drop policy if exists assignments_self_read on shift_assignments;
create policy assignments_self_read on shift_assignments
  for select using (
    user_id = auth.uid()
    or bloom_has_role(array['owner','manager']::bloom_role[])
  );

drop policy if exists assignments_manager_write on shift_assignments;
create policy assignments_manager_write on shift_assignments
  for all using (bloom_has_role(array['owner','manager']::bloom_role[]))
         with check (bloom_has_role(array['owner','manager']::bloom_role[]));

-- Swaps: requester reads/inserts own; manager+ reads/decides all.
drop policy if exists swaps_requester_read on shift_swaps;
create policy swaps_requester_read on shift_swaps
  for select using (
    requester_id = auth.uid()
    or bloom_has_role(array['owner','manager']::bloom_role[])
  );

drop policy if exists swaps_requester_insert on shift_swaps;
create policy swaps_requester_insert on shift_swaps
  for insert with check (requester_id = auth.uid());

drop policy if exists swaps_manager_decide on shift_swaps;
create policy swaps_manager_decide on shift_swaps
  for update using (bloom_has_role(array['owner','manager']::bloom_role[]))
             with check (bloom_has_role(array['owner','manager']::bloom_role[]));
